apiVersion: apps/v1
kind: Deployment
metadata:
  creationTimestamp: null
  labels:
    app.kubernetes.io/created-by: application-service
    app.kubernetes.io/instance: governance-policy-addon-controller-ocyz
    app.kubernetes.io/managed-by: kustomize
    app.kubernetes.io/name: governance-policy-addon-controller-ocyz
    app.kubernetes.io/part-of: governance-policy-addon-controller
  name: governance-policy-addon-controller-ocyz
spec:
  replicas: 1
  revisionHistoryLimit: 0
  selector:
    matchLabels:
      app.kubernetes.io/instance: governance-policy-addon-controller-ocyz
  strategy: {}
  template:
    metadata:
      creationTimestamp: null
      labels:
        app.kubernetes.io/instance: governance-policy-addon-controller-ocyz
    spec:
      containers:
      - image: quay.io/redhat-user-workloads/crt-redhat-acm-tenant/governance-policy-addon-controller/governance-policy-addon-controller-ocyz@sha256:d60fd89c6c899d1caa839c056a0b4444e56b1e723fd5eb7f366a6ffc369e6571
        imagePullPolicy: Always
        name: container-image
        ports:
        - containerPort: 8080
        resources:
          requests:
            cpu: 10m
            memory: 50Mi
status: {}
