apiVersion: v1
kind: Service
metadata:
  creationTimestamp: null
  labels:
    app.kubernetes.io/created-by: application-service
    app.kubernetes.io/instance: governance-policy-addon-controller-ocyz
    app.kubernetes.io/managed-by: kustomize
    app.kubernetes.io/name: governance-policy-addon-controller-ocyz
    app.kubernetes.io/part-of: governance-policy-addon-controller
  name: governance-policy-addon-controller-ocyz
spec:
  ports:
  - port: 8080
    targetPort: 8080
  selector:
    app.kubernetes.io/instance: governance-policy-addon-controller-ocyz
status:
  loadBalancer: {}
