apiVersion: apps/v1
kind: Deployment
metadata:
  creationTimestamp: null
  name: governance-policy-addon-controller-ocyz
spec:
  selector: {}
  strategy: {}
  template:
    metadata:
      creationTimestamp: null
    spec:
      containers:
      - image: quay.io/redhat-user-workloads/crt-redhat-acm-tenant/governance-policy-addon-controller/governance-policy-addon-controller-ocyz@sha256:72b141466e2356147477fb0f377962401a84c498b475ee5e556cc29bad82eeef
        name: container-image
        resources: {}
status: {}
