apiVersion: apps/v1
kind: Deployment
metadata:
  creationTimestamp: null
  name: governance-policy-addon-controller-ocyz
spec:
  replicas: 1
  selector: {}
  strategy: {}
  template:
    metadata:
      creationTimestamp: null
    spec:
      containers:
      - image: quay.io/redhat-user-workloads/crt-redhat-acm-tenant/governance-policy-addon-controller/governance-policy-addon-controller-ocyz@sha256:fa0c18590a73461be8c5902feb386ad07a81bdbbe085320b8a10bcc7258b2aca
        name: container-image
        resources: {}
status: {}
